class Enum:
    reverse_mapping = {}
    @classmethod
    def get_value_name(cls, value: int):
        if not hasattr(cls, '_reverse_mapping'):
            cls._reverse_mapping = {
                val: name for name, val in cls.__dict__.items()
                if isinstance(val, int)
            }

        return cls._reverse_mapping.get(value, f"Unknown code: {value}")

class WalterModemState(Enum):
    OK = 0
    ERROR = 1
    TIMEOUT = 2
    NO_MEMORY = 3
    NO_SUCH_PDP_CONTEXT = 4
    NO_FREE_SOCKET = 5
    NO_SUCH_SOCKET = 6
    NO_SUCH_PROFILE = 7
    NOT_EXPECTING_RING = 8
    AWAITING_RING = 9
    BUSY = 10
    NO_DATA = 11

class WalterModemOpState(Enum):
    MINIMUM = 0
    FULL = 1
    NO_RF = 4
    MANUFACTURING = 5

class WalterModemNetworkRegState(Enum):
    NOT_SEARCHING = 0
    REGISTERED_HOME = 1
    SEARCHING = 2
    DENIED = 3
    UNKNOWN = 4
    REGISTERED_ROAMING = 5
    REGISTERED_SMS_ONLY_HOME = 6
    REGISTERED_SMS_ONLY_ROAMING = 7
    ATTACHED_EMERGENCY_ONLY = 8
    REGISTERED_CSFB_NOT_PREFERRED_HOME = 9
    REGISTERED_CSFB_NOT_PREFERRED_ROAMING = 10
    REGISTERED_TEMP_CONN_LOSS = 80

class WalterModemCMEErrorReportsType(Enum):
    OFF = 0
    NUMERIC = 1
    VERBOSE = 2
    
class WalterModemCEREGReportsType(Enum):
    OFF = 0
    ENABLED = 1
    ENABLED_WITH_LOCATION = 2
    ENABLED_WITH_LOCATION_EMM_CAUSE = 3
    ENABLED_UE_PSM_WITH_LOCATION= 4
    ENABLED_UE_PSM_WITH_LOCATION_EMM_CAUSE = 5

class WalterModemCMEError(Enum):
    EQUIPMENT_FAILURE = 0
    NO_CONNECTION = 1
    PHONE_ADAPTER_LINK_RESERVED = 2
    OPERATION_NOT_ALLOWED = 3
    OPERATION_NOT_SUPPORTED = 4
    PH_SIM_PIN_REQUIRED = 5
    PH_FSIM_PIN_REQUIRED = 6
    PH_FSIM_PUK_REQUIRED = 7
    SIM_NOT_INSERTED = 10
    SIM_PIN_REQUIRED = 11
    SIM_PUK_REQUIRED = 12
    SIM_FAILURE = 13
    SIM_BUSY = 14
    SIM_WRONG = 15
    INCORRECT_PASSWORD = 16
    SIM_PIN2_REQUIRED = 17
    SIM_PUK2_REQUIRED = 18
    MEMORY_FULL = 20
    INVALID_INDEX = 21
    NOT_FOUND = 22
    MEMORY_FAILURE = 23
    TEXT_STRING_TOO_LONG = 24
    INVALID_CHARS_IN_TEXT_STRING = 25
    DIAL_STRING_TOO_LONG = 26
    INVALID_CHARS_IN_DIAL_STRING = 27
    NO_NETWORK_SERVICE = 30
    NETWORK_TIMEOUT = 31
    NETWORK_NOT_ALLOWED_EMERGENCY_CALS_ONLY = 32
    NETWORK_PERSONALIZATION_PIN_REQUIRED = 40
    NETWORK_PERSONALIZATION_PUK_REQUIRED = 41
    NETWORK_SUBSET_PERSONALIZATION_PIN_REQUIRED = 42
    NETWORK_SUBSET_PERSONALIZATION_PUK_REQUIRED = 43
    SERVICE_PROVIDER_PERSONALIZATION_PIN_REQUIRED = 44
    SERVICE_PROVIDER_PERSONALIZATION_PUK_REQUIRED = 45
    CORPORATE_PERSONALIZATION_PIN_REQUIRED = 46
    CORPORATE_PERSONALIZATION_PUK_REQUIRED = 47
    HIDDEN_KEY_REQUIRED = 48
    EAP_METHOD_NOT_SUPPORTED = 49
    INCORRECT_PARAMETERS = 50
    SYSTEM_FAILURE = 60
    UNKNOWN_ERROR = 100
    UPGRADE_FAILED_GENERAL_ERROR = 528
    UPGRADE_FAILED_CORRUPTED_IMAGE = 529
    UPGRADE_FAILED_INVALID_SIGNATURE = 530
    UPGRADE_FAILED_NETWORK_ERROR = 531
    UPGRADE_FAILED_ALREADY_IN_PROGRESS = 532
    UPGRADE_CANCEL_FAILED_NO_UPGRADE_IN_PROGRESS = 533
    HW_CONFIG_FAILED_GENERAL_ERROR = 540
    HW_CONFIG_FAILED_INVALID_FUNCTION = 541
    HW_CONFIG_FAILED_INVALID_FUNCTION_PARAM = 542
    HW_CONFIG_FAILED_PINS_ALREADY_ASSIGNED = 54
    WRONG_STATE = 551

class WalterModemRspParserState(Enum):
    START_CR = 0
    START_LF = 1
    DATA = 2
    DATA_PROMPT = 3
    DATA_PROMPT_HTTP = 4
    DATA_HTTP_START1 = 5
    DATA_HTTP_START2 = 6
    END_LF = 7
    RAW = 8


class WalterModemCmdType(Enum):
    TX = 0
    TX_WAIT = 1
    WAIT = 2
    DATA_TX_WAIT = 3


class WalterModemCmdState(Enum):
    NEW = 2
    PENDING = 3
    RETRY_AFTER_ERROR = 4
    COMPLETE = 6

class WalterModemRspType(Enum):
    NO_DATA = 0
    OP_STATE = 1
    RAT = 2
    RSSI = 3
    SIGNAL_QUALITY = 4
    SIM_STATE = 5
    CME_ERROR = 6
    BANDSET_CFG_SET = 7
    PDP_ADDR = 8
    SOCKET_ID = 9
    GNSS_ASSISTANCE_DATA = 10
    CLOCK = 11
    MQTT = 12
    HTTP = 13
    COAP = 14
    CELL_INFO = 15
    REG_STATE = 50
